document.addEventListener("DOMContentLoaded", function() {
    var audioPlayer = document.getElementById("audio-player");
    var playpauseBtn = document.getElementById("playpause-btn");
    var volumeSlider = document.getElementById("volume-slider");
    var progressBar = document.querySelector(".progress");

    // Play/Pause Button Click Event
    playpauseBtn.addEventListener("click", function() {
        if (audioPlayer.paused || audioPlayer.ended) {
            audioPlayer.play();
            playpauseBtn.classList.remove("play");
            playpauseBtn.classList.add("pause");
        } else {
            audioPlayer.pause();
            playpauseBtn.classList.remove("pause");
            playpauseBtn.classList.add("play");
        }
    });

    // Update Progress Bar
    audioPlayer.addEventListener("timeupdate", function() {
        var duration = audioPlayer.duration;
        var currentTime = audioPlayer.currentTime;
        var progress = (currentTime / duration) * 100;
        progressBar.style.width = progress + "%";
    });

    // Volume Slider Change Event
    volumeSlider.addEventListener("input", function() {
        audioPlayer.volume = volumeSlider.value / 100;
    });
});
document.addEventListener("DOMContentLoaded", function() {
	    var audioPlayer = document.getElementById("audio-player");
	    var playpauseBtn = document.getElementById("playpause-btn");
	    var volumeSlider = document.getElementById("volume-slider");
	    var progressBar = document.querySelector(".progress");

	    // Play/Pause Button Click Event
	//     playpauseBtn.addEventListener("click", function() {
	//             if (audioPlayer.paused || audioPlayer.ended) {
	//                         audioPlayer.play();
	//                                     playpauseBtn.classList.remove("play");
	//                                                 playpauseBtn.classList.add("pause");
	//                                                         } else {
	//                                                                     audioPlayer.pause();
	//                                                                                 playpauseBtn.classList.remove("pause");
	//                                                                                             playpauseBtn.classList.add("play");
	//                                                                                                     }
	//                                                                                                         });
	//
	//                                                                                                             // Update Progress Bar
	//                                                                                                                 audioPlayer.addEventListener("timeupdate", function() {
	//                                                                                                                         var duration = audioPlayer.duration;
	//                                                                                                                                 var currentTime = audioPlayer.currentTime;
	//                                                                                                                                         var progress = (currentTime / duration) * 100;
	//                                                                                                                                                 progressBar.style.width = progress + "%";
	//                                                                                                                                                     });
	//
	//                                                                                                                                                         // Volume Slider Change Event
	//                                                                                                                                                             volumeSlider.addEventListener("input", function() {
	//                                                                                                                                                                     audioPlayer.volume = volumeSlider.value / 100;
	//                                                                                                                                                                         });
	//                                                                                                                                                                         });
	//                                                                                                                                                                         document.addEventListener("DOMContentLoaded", function() {
	//                                                                                                                                                                             var audioPlayer = document.getElementById("audio-player");
	//                                                                                                                                                                                 var playpauseBtn = document.getElementById("playpause-btn");
	//                                                                                                                                                                                     var volumeSlider = document.getElementById("volume-slider");
	//                                                                                                                                                                                         var progressBar = document.querySelector(".progress");
	//
	//                                                                                                                                                                                             // Play/Pause Button Click Event
	//                                                                                                                                                                                                 playpauseBtn.addEventListener("click", function() {
	//                                                                                                                                                                                                         if (audioPlayer.paused || audioPlayer.ended) {
	//                                                                                                                                                                                                                     audioPlayer.play();
	//                                                                                                                                                                                                                                 playpauseBtn.classList.remove("play");
	//                                                                                                                                                                                                                                             playpauseBtn.classList.add("pause");
	//                                                                                                                                                                                                                                                     } else {
	//                                                                                                                                                                                                                                                                 audioPlayer.pause();
	//                                                                                                                                                                                                                                                                             playpauseBtn.classList.remove("pause");
	//                                                                                                                                                                                                                                                                                         playpauseBtn.classList.add("play");
	//                                                                                                                                                                                                                                                                                                 }
	//                                                                                                                                                                                                                                                                                                     });
	//
	//                                                                                                                                                                                                                                                                                                         // Update Progress Bar
	//                                                                                                                                                                                                                                                                                                             audioPlayer.addEventListener("timeupdate", function() {
	//                                                                                                                                                                                                                                                                                                                     var duration = audioPlayer.duration;
	//                                                                                                                                                                                                                                                                                                                             var currentTime = audioPlayer.currentTime;
	//                                                                                                                                                                                                                                                                                                                                     var progress = (currentTime / duration) * 100;
	//                                                                                                                                                                                                                                                                                                                                             progressBar.style.width = progress + "%";
	//                                                                                                                                                                                                                                                                                                                                                 });
	//
	//                                                                                                                                                                                                                                                                                                                                                     // Volume Slider Change Event
	//                                                                                                                                                                                                                                                                                                                                                         volumeSlider.addEventListener("input", function() {
	//                                                                                                                                                                                                                                                                                                                                                                 audioPlayer.volume = volumeSlider.value / 100;
	//                                                                                                                                                                                                                                                                                                                                                                     });
	//                                                                                                                                                                                                                                                                                                                                                                     });
	//                                                                                                                                                                                                                                                                                                                                                                     document.addEventListener("DOMContentLoaded", function() {
	//                                                                                                                                                                                                                                                                                                                                                                         var audioPlayer = document.getElementById("audio-player");
	//                                                                                                                                                                                                                                                                                                                                                                             var playpauseBtn = document.getElementById("playpause-btn");
	//                                                                                                                                                                                                                                                                                                                                                                                 var volumeSlider = document.getElementById("volume-slider");
	//                                                                                                                                                                                                                                                                                                                                                                                     var progressBar = document.querySelector(".progress");
	//
	//                                                                                                                                                                                                                                                                                                                                                                                         // Play/Pause Button Click Event
	//                                                                                                                                                                                                                                                                                                                                                                                             playpauseBtn.addEventListener("click", function() {
	//                                                                                                                                                                                                                                                                                                                                                                                                     if (audioPlayer.paused || audioPlayer.ended) {
	//                                                                                                                                                                                                                                                                                                                                                                                                                 audioPlayer.play();
	//                                                                                                                                                                                                                                                                                                                                                                                                                             playpauseBtn.classList.remove("play");
	//                                                                                                                                                                                                                                                                                                                                                                                                                                         playpauseBtn.classList.add("pause");
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                             audioPlayer.pause();
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                         playpauseBtn.classList.remove("pause");
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     playpauseBtn.classList.add("play");
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
	//
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Update Progress Bar
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         audioPlayer.addEventListener("timeupdate", function() {
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 var duration = audioPlayer.duration;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         var currentTime = audioPlayer.currentTime;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 var progress = (currentTime / duration) * 100;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         progressBar.style.width = progress + "%";
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
	//
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Volume Slider Change Event
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     volumeSlider.addEventListener("input", function() {
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             audioPlayer.volume = volumeSlider.value / 100;
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
	//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
//
